#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_SIDNEY      0
#define MUGSHOT_PHOEBE      1
#define MUGSHOT_GLACIA      2
#define MUGSHOT_DRAKE       3
#define MUGSHOT_CHAMPION    4
#define MUGSHOT_MAY    		5
#define MUGSHOT_BRENDAN    	6
#define MUGSHOT_WALLY    	7
#define MUGSHOT_STEVEN  	8
#define MUGSHOT_RED  		9
#define MUGSHOT_LEAF  		10


#define MUGSHOTS_COUNT      11

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H