#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_SIDNEY      0
#define MUGSHOT_PHOEBE      1
#define MUGSHOT_GLACIA      2
#define MUGSHOT_DRAKE       3
#define MUGSHOT_CHAMPION    4
#define MUGSHOT_MAY    		5
#define MUGSHOT_BRENDAN    	6
#define MUGSHOT_WALLY    	7
#define MUGSHOT_STEVEN  	8
#define MUGSHOT_RED  		9
#define MUGSHOT_LEAF  		10
#define MUGSHOT_ROXANNE		11
#define MUGSHOT_BRAWLY  	12
#define MUGSHOT_WATTSON  	13
#define MUGSHOT_FLANNERY  	14
#define MUGSHOT_NORMAN  	15
#define MUGSHOT_WINONA  	16
#define MUGSHOT_TATE_LIZA  	17
#define MUGSHOT_JUAN  		18


#define MUGSHOTS_COUNT      19

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H